%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.4

-ifndef(all_pb).
-define(all_pb, true).

-define(all_pb_gpb_version, "4.19.4").

-ifndef('M_1101_TOC_PB_H').
-define('M_1101_TOC_PB_H', true).
-record(m_1101_toc,
        {cmd                    :: non_neg_integer() | undefined, % = 1, required, 32 bits
         error_code             :: non_neg_integer() | undefined, % = 2, required, 32 bits
         description            :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-ifndef('M_1001_TOS_PB_H').
-define('M_1001_TOS_PB_H', true).
-record(m_1001_tos,
        {
        }).
-endif.

-ifndef('M_1001_TOC_PB_H').
-define('M_1001_TOC_PB_H', true).
-record(m_1001_toc,
        {time                   :: non_neg_integer() | undefined % = 1, required, 32 bits
        }).
-endif.

-ifndef('M_1002_TOS_PB_H').
-define('M_1002_TOS_PB_H', true).
-record(m_1002_tos,
        {
        }).
-endif.

-ifndef('M_1002_TOC_PB_H').
-define('M_1002_TOC_PB_H', true).
-record(m_1002_toc,
        {n                      :: unicode:chardata() | undefined, % = 1, required
         e                      :: unicode:chardata() | undefined % = 2, required
        }).
-endif.

-ifndef('M_1003_TOS_PB_H').
-define('M_1003_TOS_PB_H', true).
-record(m_1003_tos,
        {username               :: unicode:chardata() | undefined, % = 1, required
         password               :: unicode:chardata() | undefined % = 2, required
        }).
-endif.

-ifndef('M_1003_TOC_PB_H').
-define('M_1003_TOC_PB_H', true).
-record(m_1003_toc,
        {
        }).
-endif.

-ifndef('M_1004_TOC_PB_H').
-define('M_1004_TOC_PB_H', true).
-record(m_1004_toc,
        {
        }).
-endif.

-endif.
